spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nature?useUnicode=true;characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Skwdkwla153@
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:tcp://localhost/~/nature
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    hibernate:
      type:
        descrpitor:
          .sql: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#jwt:
server:
  servlet:
    session:
      timeout: 4h
#  secret: 12345678901234567890123456789012