spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/nature
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    hibernate:
      type:
        descrpitor:
          .sql: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace
